#!/bin/bash
if [[ $@ == *"-cp"* ]] ; then
curdir=$(dirname "$0")
for i in "$@" ; do
case "$i" in
-Djava.library.path=*)
LIBRARYPATH="${i#*=}"
esac
done
cp "$curdir"/../libglfw.dylib "$LIBRARYPATH"/libglfw.dylib
cp "$curdir"/../libopenal.dylib "$LIBRARYPATH"/libopenal.dylib
exec open -n -W "$curdir"/Minecraft.app --args "$PWD" "$@"
fi
