#!/bin/bash
if [[ $@ == *"-cp"* ]] ; then
curdir=$(dirname "$0")
lwjgldir="$TMPDIR"/lwjgl"$USER"/3.3.1-build-7
mkdir -p "$lwjgldir"
ln -s ~/Library/Application\ Support/minecraft/runtime/java-runtime-gamma/mac-os-arm64 ~/Library/Application\ Support/minecraft/runtime/java-runtime-gamma/mac-os
rm ~/Library/Application\ Support/minecraft/libraries/org/lwjgl/lwjgl-glfw/*/*natives*
rm ~/Library/Application\ Support/minecraft/libraries/org/lwjgl/lwjgl-openal/*/*natives*
cp "$curdir"/../libglfw.dylib "$lwjgldir"/libglfw.dylib
cp "$curdir"/../libglfw.dylib "$lwjgldir"/libglfw_async.dylib
cp "$curdir"/../libopenal.dylib "$lwjgldir"/libopenal.dylib
exec open -n -W "$curdir"/Minecraft.app --args "$PWD" "$@"
fi
